### ISSUE TITLE
1.24 fails to build in 2021

### ISSUE THREAD

**Issue by bmwiedemann** [skyfielders/python-skyfield#415] opened 2020-07-26 02:30 UTC
While working on reproducible builds for openSUSE, I found that
our python-skyfield-1.24 package fails tests in 2021
because calls to `load.timescale` without `builtin=True` are used a lot:

```
grep load.timescale skyfield/tests/*.py|grep -v builtin=True | wc -l
107
```
and these try to pull updated data from ftp://cddis.nasa.gov and that fails in our builds, because we disable the network to ensure reproducible results.

See also https://reproducible-builds.org/ for why this matters.

**Comment by brandon-rhodes** [comment] 2020-07-26 02:42
I had been looking at those for a while and thinking about fixing them! I was vacillating between building all those timescale with `builtin=True`, or just creating one timescale for all tests to share, making them somewhat faster but at the risk to entanglement.

I should probably go with `builtin=True` for now since it's a simple textual substitution without any implications for test correctness. I'll see about getting to that within a few days.

I do want at least one test that will fail if those builtin files get too old, to warn me to update them before a release. To stop that from affecting your results, I guess I'll write that as a standalone script outside the main package, and run it only in my own CI.

**Comment by bnavigator** [comment] 2020-07-26 07:59
> I do want at least one test that will fail if those builtin files get too old, to warn me to update them before a release. To stop that from affecting your results, I guess I'll write that as a standalone script outside the main package, and run it only in my own CI.

You could also keep it in the regular test suite and provide a way to skip that particular test by a command line parameter or environment variable, which we can set in the openSUSE build. Does assay support test deselection like `-k "not future_testdata_fail"` in pytest?

**Comment by bmwiedemann** [comment] 2020-07-26 10:58
For the substitution you can use
```perl
perl -i -pe 'if(!/builtin=True/) {
  s/load.timescale\(([^)])/load.timescale(builtin=True, $1/ ;
  s/load.timescale\(\)/load.timescale(builtin=True)/;
}' skyfield/tests/test*
```

Then 70 something tests start to fail because results deviate from previously expected results.

**Comment by bnavigator** [comment] 2020-07-27 09:45
The problem is not, that the tests try to download new data files instead of using the offline provided ones. The downloaded files would be the same. The problem is, that the tests don't accept files that have expired by the virtual system time which is set by the reproducible build check.

**Comment by brandon-rhodes** [comment] 2020-07-28 02:04
Could I have a bit of clarification about the problem? @bmwiedemann:

> these try to pull updated data from ftp://cddis.nasa.gov and that fails in our builds, because we disable the network to ensure reproducible results.

@bnavigator:

> The problem is not, that the tests try to download new data files…

This pair of statements leaves me confused about whether the network download is among the problems here or not. (Yes, I expect that it will become clear when I have time later this week to sit down and try things out with the date advanced a few years; but in the meantime I thought I would ask.)

**Comment by bnavigator** [comment] 2020-07-28 13:49
Okay, it may be a bit confusing. Here are some facts to clarify:

1. openSUSE Build Service does build the packages offline. Which means all source data must be provided beforehand. No ad-hoc downloading of files. Reasoning from reproducible builds perspective: [no volatile inputs](https://reproducible-builds.org/docs/volatile-inputs/)
2. If the skyfield test suite cannot find the data in the current directoy and `builtin=True` is not specified, it tries to download the data ad-hoc, which fails on OBS
3. The same is true if the data is present but Skyfield finds that the data is outdated. This is the case for @bmwiedemanns reproducible build test which sets the system time to a future date.
4. With introducing `builtin=True` the download try is skipped, but the actual tests fail (https://github.com/skyfielders/python-skyfield/issues/415#issuecomment-663973326), because the data virtually *is* outdated.

So to me, the logical solution is to skip the expected failing test for the reproducible build effort. With https://github.com/brandon-rhodes/assay/pull/10 there would be a way to skip certain tests by specifying them in the specfile when calling assay.

Another possibility would be to modify the expiration dates in the OBS provided offline data, (unless some tests check for a correct expiration date).

Either way, the produced package should be the same. Whether the tests are run and passing or if they are skipped. The test suite just cannot fail, because then no package at all will be produced. So my question to @bmwiedemann is: Would it be okay to skip the entire test suite if a system date beyond the expiry date is encountered? Granted, this would introduce the possibility to have a non-functional package in openSUSE, if nobody cares to maintain it after the expiry date and no checks against the current systems will be run by default then. So I would say no.

**Comment by brandon-rhodes** [comment] 2020-08-01 23:17
A surprise development: the new Skyfield 1.26 that I just released entirely disposes of the idea of auto-downloading out-of-date files, and also switches to builtin timescale files by default.

This was inspired by the fact that the `deltat.data` file as NASA has not been updated since February, presumably because of the pandemic. And if that’s not fixed, then starting in February or March 2021 all older Skyfield versions will start re-downloading the files every time they’re run.

I conclude that it was a mistake to try to automatically perform network I/O, instead of letting users themselves make decisions about how to keep files up-to-date. So the feature is gone and the code is happily simpler than it was two days ago!

Let me know if the new version seems to work in your container; it works in mine, but there could still be a rough edge lurking that I haven’t found.

**Comment by bnavigator** [comment] 2020-08-02 15:16
I really appreciate your effort in supporting networkless build and operation. :+1: 

I can confirm, that skyfield-1.26 builds successfully on openSUSE with time set into the future:

```
~/src/osc/devel:languages:python:numeric/python-skyfield/ > osc build --noservice --clean --vm-type=kvm --build-opt=--vm-custom-opt="-rtc base=2021-08-02T00:00:00"
```
[buildlog2021.txt](https://github.com/skyfielders/python-skyfield/files/5012313/buildlog2021.txt)


Regarding the handling of expired files: I think it would still be warranted to print a warning or even throw an error (if so desired 
by configuration) for outdated local files.

**Comment by brandon-rhodes** [comment] 2020-08-02 15:18
> Regarding the handling of expired files: I think it would still be warranted to print a warning or even throw an error (if so desired by configuration) for outdated local files.

That’s a good idea! Let’s leave this issue open, and tomorrow I’ll close it with a commit that adds documentation showing both approaches: code folks can paste into their app that prints a warning, and code that will actually throw an error, if a file is outdated. That way folks can have give their apps either grade of protection without needing to go look up the Python maneuvers required.

**Comment by bmwiedemann** [comment] 2020-08-09 20:01
python-skyfield-1.26 builds fine in my tests even in 2035.

**Comment by brandon-rhodes** [comment] 2020-08-17 23:47
Thanks, everyone, for validating that things work now; I'll close this issue.

As you can see from the above commit, I did try tweaking the documentation a bit to provide explicit checks for whether the files might be considered "old". But I didn't wind up providing sample code for issuing warnings or exiting with an error; when I tried to get started on the subject, it didn't feel Skyfield-specific, and was merely covering generic Python topics like “how to issue a warning” or “how to exit with an error” that are covered far better elsewhere on the Web.

**Closed by brandon-rhodes** 2020-08-17 23:47 UTC
