### ISSUE TITLE
Propagation seems to be wrong for TLEs with low eccentricity

### ISSUE THREAD

**Issue by alepinio** [skyfielders/python-skyfield#235] opened 2019-01-30 20:59 UTC
Hi,

I'm stuck with the following. I'm doing many orbit calculations for polar earth satellites and I can't understand why, when the eccentricity falls below some value, the perigee is not where it is supposed to be.

**OK case:**
1) Take the following TLE
```
1 99999U          19001.00000000 -.00000000  00000-0  00000-0 0 00001
2 99999 090.0000 270.0000 0100000 000.0000 000.0000 14.00000000000000
```
2) Propagate the TLE to complete nearly an orbit using, say `dt = 1 min` , and compute distances for each position to the center of the Earth. As right ascension of ascending node is `0.0` and the argument of perigee is also `0.0`, perigee position should be a point on the equator.
3) Find the lowest distance, that's the perigee. Plot it.
4) You will find that the perigee happens for a point very nearly to the equator (OK because right ascension of ascending node is `0.0` and the argument of perigee is also `0.0`).

**NOT OK case:**
1) Take the following TLE (only differs in eccentricity from the former, now is `0010000`)
```
1 99999U          19001.00000000 -.00000000  00000-0  00000-0 0 00001
2 99999 090.0000 270.0000 0010000 000.0000 000.0000 14.00000000000000
```
2) Repeat step 2 from OK case.
2) Repeat step 3 from OK case.
3) For me, perigee is not a point very nearly to the equator! (not OK, given that right ascension of ascending node is `0.0` and the argument of perigee is also `0.0` then the perigee should a point very near to the equator). The lowest distance to the center of the Earth occurs for me at an angle of approx. 60.3 degrees from the ascending node.

**What am I doing wrong?**

THX, Alejandro

**Comment by brandon-rhodes** [comment] 2019-01-31 12:38
I'm not sure — I've always used the numbers from real satellites, I've not tried setting up artificial situations. The first thing I would do would be to make a rotatable 3D plot of a full orbit. It's been a while since I've tried to set up interactive 3D plots in Python, but a search should bring up pages like this one that might help you get started:

https://stackoverflow.com/questions/33436221/displaying-rotatable-3d-plots-in-ipython-or-ipython-notebook

I always try to get a good plot of a situation first, before asking bigger questions, so that I can see a more full picture of what's going on.

**Comment by brandon-rhodes** [comment] 2019-01-31 14:09
Thank you! I'll take a look at it this evening. I wonder if one of those Jupyter interactive sliders would let us vary that TLE parameter and see the orbit redraw into different shapes as we adjust it?

**Comment by kerel-fs** [comment] 2019-05-21 22:48
> I wonder if one of those Jupyter interactive sliders would let us vary that TLE parameter and see the orbit redraw into different shapes as we adjust it?

Yes. :)
I've created this [notebook](https://gitlab.com/kerel-fs/jupyter-notebooks/blob/master/propagators/skyfield_issue235.ipynb) [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gist/kerel-fs/b10476457aab4e61378419977c664dda/master) to generate the following animation.
You get an interactive version of this if you follow the "launch on binder" link.

![output](https://user-images.githubusercontent.com/10089607/58133277-cf972700-7c23-11e9-94b5-49d218bf653f.gif)

Maybe this visualization can aid at understanding if the observed change in argument of perigee is an actual issue in the propagation or some other (expected?) effect.

**Comment by brandon-rhodes** [comment] 2019-05-25 22:39
Thank you for the visualization, @kerel-fs! I've been too busy this spring to try tackling this issue, and I suspect that SGP4 simply does not do well with non-realistic orbits and maybe was not designed to; but I'm happy to see conversation continue.

**Comment by MichaelRThompson** [comment] 2019-06-25 04:19
Confirmed the above results with the my own SGP4 propagator.  It's not something inherently wrong with the propagator.

SGP4 takes into account multiple perturbations that are messing with your argument of perigee.  As your orbit gets closer to circular (a lower eccentricity value), argument of perigee becomes more and more sensitive given that it's closer to a circular orbit, where argument of perigee is pretty much undefined.

For your two test cases:

- Eccentricity - 0.01
Argument of perigee varies between ~355 and 15 degrees. A 20 degree range.

- Eccentricity - 0.001
Argument of perigee varies between ~315 and 90 degrees. A 135 degree range.

You're approaching your problem with the assumption that your argument of perigee is going to stay relatively constant, but in reality it is varying by quite a bit.  Your two test cases are at about 800 km altitude, and the perturbations due to things like J2 are still quite strong there.

I created a 3rd test case using the TLE:
```
1 99999U          19001.00000000 -.00000000  00000-0  00000-0 0 00001
2 99999 090.0000 270.0000 0010000 000.0000 000.0000 5.00000000000000
```

This is a much higher orbit, and the argument of perigee is bounded between ~5 and 45 degrees.

As you can see, your issue isn't really a problem with the propagator, it's an issue with perturbations.  Especially at low eccentricities, your argument of perigee can become really sensitive to perturbations, and your periapsis can move around a good bit.

**Comment by brandon-rhodes** [comment] 2019-06-25 20:25
Thank you for the analysis, @MichaelRThompson! Can anyone suggest an improvement to the documentation that might cover this case? For now I'll close the issue, but if anyone wants to submit some updated docs, please feel free to do so; otherwise, hopefully Google will lead folks to this issue who have a similar question.

**Closed by brandon-rhodes** 2019-06-25 20:25 UTC

**Comment by MichaelRThompson** [comment] 2019-06-26 02:41
I'm not sure that this case specifically needs to be addressed, but looking over the documentation, a quick introduction to the SGP4 propagator could be helpful, probably on the Earth Satellites page [here](https://rhodesmill.org/skyfield/earth-satellites.html).  Just an overview of what kind of perturbations are included and what that can do to some of your orbital elements.

I think it could fit it nicely with the limitations section up at the top.  Let me know if you'd like any help in writing something up.
