### ISSUE TITLE
Different ways to calculate the longitude

### ISSUE THREAD

**Issue by heratspace** [skyfielders/python-skyfield#291] opened 2019-10-02 16:21 UTC
I am not sure if this is a bug or a misundersting from my side (probably the last_

I am trying to calculate the longitude of a planet and I get different results in if I do 
`osculating_elements_of((planet - sun).at(t).true_longitude`  or `(planet - sun).at(t).ecliptic_latlon()[1]`

I thought it might be a problem with the equinox, so I calculated the difference between the longitude for two planets and still both methods do not match. 

Any ideas?

**Comment by GammaSagittarii** [comment] 2019-10-02 17:21
Please use this way for say mercury:
astrometric_mercury = earth.at(t).observe(mercury)
apparent_mercury = astrometric_mercury.apparent()
lat, lon, d = apparent_mercury.ecliptic_latlon(epoch='date')
That is most likely what you need.

**Comment by brandon-rhodes** [comment] 2019-10-02 17:32
@heratspace Computing osculating elements produces a less accurate version of the planet's orbit than the one used in the ephemeris. I would suggest using the ephemeris to produce positions, then do math on those positions.

Was there documentation that led you to think you should generate osculating elements for a latitude determining? If so, let me know which ones they are, and I'll get them fixed. Thanks!

**Comment by heratspace** [comment] 2019-10-02 19:56
I found this by chance. I was calculating the OsculatingElements to look at some "instantenous" orbital parameters and I was using `ecliptic_latlon` to find the longitude. Then I found that there was an attribute (`true_longitude`) in the former object and I could skip a calculation step. 

When these values did not match, I started checking if I was missing something (changes in the ecliptic, inclinatio of the orbit, etc) and nothing seems to fix it. That is when I wrote. I am curious to know. For example at `tt=2451545` the difference for the earth longitude is 0.004, but for saturn is 0.46, which is a lot. I wonder at which step this calculation error apears.

**Comment by brandon-rhodes** [comment] 2019-10-02 20:41
> When these values did not match, I started checking if I was missing something … and nothing seems to fix it

The problem is that the true longitude is a fictional concept that doesn't reflect the actual position of the planet. Here's some background on its definition:

https://en.wikipedia.org/wiki/True_longitude

**Comment by heratspace** [comment] 2019-10-02 21:22
I followed the osculating elements code to find out how this was calculated and indeed found that that is was calculated as described in the link you posted, by previously obtaining the h, e and n vectors. But still, the longitude should be the same in both cases

I run the calculation for 30 years (a little bit more of saturns period), and the difference between one way to calculate and the other has a clear bias (0.5). I expected if this was just an accuracy problema, one result would sometimes above while other times below the other. But not only has a clear bias but it is correlated with the position in the orbit. That is why I thought there is a systematic difference

**Comment by brandon-rhodes** [comment] 2019-10-03 10:36
> But still, the longitude should be the same in both cases

I am not sure why they should be the same. Could you outline, mathematically, why you think the two longitudes would have the same value for Saturn?

**Comment by heratspace** [comment] 2019-10-03 16:09
Let's say I have a vector `Ro` that points from the sun to the planet. Then the longitude is projecting that vector `Ro` on the plane of the ecliptic and measuring the angle to the vernal equinox. That is what `ecliptic_latlon` does.

And according to [1], which is the book cited in the code, "the true longitude is the angle between `I` and `Ro` measured eastward to the ascending node (if it exists) and then in the orbital plane to `Ro`." where "`I` is the unit vector that points to the vernal equinox" 

I think is the same, or is there any subtleties that I am not seeing?

[1] Bate, Mueller, & White. Fundamentals of Astrodynamics (1971), Section 2.4, pgs. 61-64

**Comment by brandon-rhodes** [comment] 2019-10-03 19:49
The subtlety is that the angles are in two different planes. Ecliptic longitude is along the ecliptic, while "true longitude" is in the plane of the planet's own orbit ("in the orbital plane", in the book). The two planes are the same only for the Earth; all other planets have orbits at least slightly inclined to our own.

**Comment by heratspace** [comment] 2019-10-04 00:29
I appreciate the time you spend answer this. I will try to convert between the two planes to see if I can recover that.

**Comment by brandon-rhodes** [comment] 2019-10-10 12:34
In the meantime I'm going to close this issue since it's not currently pending any action to be taken in Skyfield's code. Feel free to continue the discussion here by commenting further, though!

**Closed** 2019-10-10 12:35 UTC

**Comment by karthikeyadarbha** [comment] 2023-05-09 07:17
> astrometric_mercury = earth.at(t).observe(mercury)
> apparent_mercury = astrometric_mercury.apparent()
> lat, lon, d = apparent_mercury.ecliptic_latlon(epoch='date')


So, tried this and I see a diff when compared the value against astrological websites. Also, how to identify retrograde motion using this formula ?
