### ISSUE TITLE
\lib\site-packages\skyfield\functions.py:77: RuntimeWarning

### ISSUE THREAD

**Issue by dataadvisor** [skyfielders/python-skyfield#500] opened 2020-12-12 22:10 UTC
Hello Brandon,

Today I was working with the Skyfiled, and I've got the following warning. I believe you should handle the exception.
```python
e = ephemeris[399]
obj = ephemeris[399]
coordinates = e.at(t).observe(obj).radec()
```

>**.\lib\site-packages\skyfield\functions.py:77: RuntimeWarning: invalid value encountered in double_scalars
  theta = arcsin(z / r)**

You might be asking why I am calculating **geocentric astrometric coordinates of earth** !!

Actually, I do not, It was happened by mistake. Then I got curious and I checked **geocentric astrometric position** as below:
```python
e = ephemeris[399]
obj = ephemeris[399]
positions = e.at(t).observe(obj).position.au
```
And the result was successful **[0.0, 0.0, 0.0]**. As logically, we can guess.

Finally, I guess you should handle the exception somewhere in your code to get off that warning in the previous code and get a logical result. (Maybe it is a division by zero exception).

Best,

**Comment by brandon-rhodes** [comment] 2020-12-12 22:40
> I guess you should handle the exception somewhere in your code to get off that warning

The message, it turns out, is a warning and not an exception. There are two big differences. First: the program keeps going, as can be confirmed with a `print`.

```
from skyfield.api import load
ts = load.timescale()
t = ts.now()
ephemeris = load('de421.bsp')
e = ephemeris[399]
obj = ephemeris[399]
coordinates = e.at(t).observe(obj).radec()
print(coordinates)
```
This results in:
```
/home/brandon/skyfield/skyfield/functions.py:77: RuntimeWarning: invalid value encountered in double_scalars
  theta = arcsin(z / r)
(<Angle 00h 00m 00.00s>, <Angle nan>, <Distance 0.0 au>)
```
Since the `print()` runs, the program survived and did not encounter an exception.

Second: because this is not an exception, it cannot be caught. If you will try putting a `try…except` around the statement yourself, I think you will be able to confirm that you cannot catch the warning; it is transparent to the Skyfield code.

There is probably a way to ask NumPy to promote warnings to exceptions, but in general libraries like Skyfield are not supposed to set global NumPy options for their own purposes; instead, end-user code is supposed to be in full control.

My understanding, then, is that there is nothing Skyfield can do that will improve the situation? Please run your own checks and see if I am correct. If I am wrong, then simply provide the sample code that you think Skyfield should run that handles this case differently, and we can try it out. Thanks!

**Comment by dataadvisor** [comment] 2020-12-12 22:47
Thank you. I will inform you.

Best,

**Comment by brandon-rhodes** [comment] 2020-12-13 18:11
After making several experiments yesterday that slowed the function down too much for this edge case, I realized this morning that it maybe could be remedied with a single addition operation! The performance impact is small enough that I've gone ahead and committed the fix. Feel free to install from the repository to test the solution out:
```
pip install https://github.com/skyfielders/python-skyfield/archive/master.zip
```

**Comment by dataadvisor** [comment] 2020-12-14 02:56
He Brandon,

I saw your solution. Actually, I was going to post the same here. But after all, look at the following solution too:
If you change the ```to_spherical(xyz)``` function to something like:
```python
def to_spherical(xyz):
    """Convert ``[x y z]`` to spherical coordinates ``(r, theta, phi)``.

    ``r`` - vector length
    ``theta`` - angle above (+) or below (-) the xy-plane
    ``phi`` - angle around the z-axis

    Note that ``theta`` is an elevation angle measured up and down from
    the xy-plane, not a polar angle measured from the z-axis, to match
    the convention for both latitude and declination.

    """
    r = length_of(xyz)
    x, y, z = xyz
    if r.all() == array([0.0]):
        theta = nan
    else:
        theta = arcsin(z / r)
    phi = arctan2(y, x) % tau
    return r, theta, phi
```

It also solves the problem. I do not think it will have such an impact on performance.

As a reminder, in your solution, because you didn't use ```import numpy as np```, so you should import ```float64```, and ```finfo``` in the top of ```function.py```
and use:
```python
_tiny = finfo(float64).tiny
```
then, it's work.

Best,

**Comment by dataadvisor** [comment] 2020-12-14 05:07
Hello Again,

Please check the following Runtimewarnings too:
```python
D:\anaconda3\lib\site-packages\skyfield\relativity.py:111: RuntimeWarning: invalid value encountered in true_divide
  u1 = position / dis
D:\anaconda3\lib\site-packages\skyfield\relativity.py:185: RuntimeWarning: invalid value encountered in double_scalars
  cosd = dot / (p1mag * vemag)
D:\anaconda3\lib\site-packages\skyfield\functions.py:83: RuntimeWarning: invalid value encountered in double_scalars
  phi = arctan2(y, x) % tau
```

They happen when we calculate the geocentric apparent coordinates of Earth.
```python
e = ephemeris[399]
e.at(t).observe(e).apparent()
```
This type of calculation makes no sense, but everything should take into our account.

I believe your solution (adding tiny float for preventing division by zero) will work here too.

Best,

**Comment by brandon-rhodes** [comment] 2020-12-14 13:59
> It also solves the problem. I do not think it will have such an impact on performance.

It doesn’t look like it would work when there is a whole array of positions instead of a single x,y,z coordinate — Skyfield’s tests should catch that, did you try running them against your proposed solution? Let me know if I should expand the README to talk more about testing.

> As a reminder, do not forget to add…

Happily, the tests will let me know if I forget any imports! I wonder if I should add `_tiny` to `functions.py` or some other central location. I’ll try out your suggestions after writing some tests for the zero-vector case, and link to this issue.

**Comment by brandon-rhodes** [comment] 2020-12-14 15:26
> Just make the following changes…

I have written a test which successfully requires me to make the fixes you suggest to `relativity.py`!

But I cannot confirm your suggestion that the `arctan2()` call needs adjustment in `functions.py`. I added a print statement, and those two values are both `0.0` when I try running `apparent().radec()` on a zero vector, and `0.0, 0.0` seems to cause no problem for `arctan2()` under my version of NumPy.

Could you print the values you get, and also specify your version of NumPy, so that I can try to also get a warning from that line?

**Comment by dataadvisor** [comment] 2020-12-14 15:54
You are hundred percent right about ```arctan2```. I couldn't produce the same warning that I before did.
I also tested this function outside of Skyfiled, and I didn't get any warning.

But the question is, why I got the warning before. I used ```_tiny``` solution for ```relativity.py``` (lines 111 and 185), so now I didn't get any warning in ```function.py```. But before these changes, I got the warning.

Anyway, my ***numpy version is 1.19.2**.

**Comment by brandon-rhodes** [comment] 2020-12-14 15:56
Thanks for double-checking! If we can't get that warning now, let's go ahead and close the issue; the other fixes might have eliminated the need to do anything to `arctan2()`. If you see a new warning in the future, simply open a new issue or re-open this one!

**Closed by brandon-rhodes** 2020-12-14 15:56 UTC

**Comment by dataadvisor** [comment] 2020-12-14 16:00
Of course. Thank you.
Until then.
