### ISSUE TITLE
some planets rise and sets not found

### ISSUE THREAD

**Issue by dyk74** [skyfielders/python-skyfield#918] opened 2023-11-20 10:50 UTC
Hello, I'm trying to calculate the rise and set for every planet on the Solar System but for some planets doesn't work (i.e Jupiter and Neptune).
This is part of the code:

from skyfield import api
from skyfield import almanac
from datetime import datetime
ts = api.load.timescale()

loc= api.wgs84.latlon(_[canceled]_, _[canceled]_)
eph = api.load('de421.bsp')
sun, earth = eph['sun'], eph['earth']
t0 = ts.utc(2023, 11, 17)
t1 = ts.utc(2023, 11, 18)
Jupiter=almanac.risings_and_settings(eph,eph['Jupiter'],loc)  ==> **the error is here...**
Jupiter_t,Jupiter_y=almanac.find_discrete(t0,t1,Jupiter)

Thank you

**Comment by Bernmeister** [comment] 2023-11-20 11:33
Try swapping `'Jupiter'` with `'JUPITER BARYCENTER'`.

**Comment by brandon-rhodes** [comment] 2023-11-21 23:12
@dyk74 — Could you be more specific about the problem you are seeing? Please either share the error message you are getting, or else explain how the output of your script differs from what you would like to see instead.

**Comment by dyk74** [comment] 2023-11-25 16:15
Hello,
my project is to know when a planet is visible during the night. I mean after the sunset (or the planet rise) until the sunrise during a month; if the planet rise during the day and sets before the sunset the software will write "not visible" in the other case just only the visibility date/hour.
Hoping it's clear :)

**Comment by brandon-rhodes** [comment] 2024-01-13 14:38
@dyk74 — Could you be more specific about the problem you are seeing? The exact text of the error message is necessary, so that folks can see what the problem is and help you fix it.

**Comment by brandon-rhodes** [comment] 2024-02-04 02:55
Since we have not been given the specific error message, we don't have enough information to address this issue, so I'm going to go ahead and close it for now. But please feel free to comment further here on the issue, even once it's closed, if you do find the error message text and would like to share it!

**Closed by brandon-rhodes** 2024-02-04 02:55 UTC
Labels: more information needed
