### ISSUE TITLE
SSL issues with Leap_Second.dat source

### ISSUE THREAD

**Issue by rtphokie** [skyfielders/python-skyfield#317] opened 2020-01-05 00:49 UTC
Python Version:  3.7.3
OS: Mac OS Catalina version 10.15.2
SkyField version: 1.16

The automation which which attempts to fetch leap second information from the International Earth rotation and Reference Systems Service is running into certificate problems.  Note this only happens when the Leap_Second.dat file is not cached locally.

`OSError: cannot get https://hpiers.obspm.fr/iers/bul/bulc/Leap_Second.dat because <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
`

The problem is not with the Paris Observatory website but in Python 3.7 specifically with how **urlib2.urlopen()** accesses some https sites.  For what it is worth, **requests.get()** fetches this URL (https://hpiers.obspm.fr/iers/bul/bulc/Leap_Second.dat) without any problem.

A workaround is to manually fetch the file and save it locally.

**Comment by brandon-rhodes** [comment] 2020-01-05 03:22
Thanks for letting me know! Do other Python versions work, break, or is 3.7 the only one you've been able to test so far?

**Comment by Mausy5043** [comment] 2020-01-25 13:03
I have the same issue with Python 3.6.6 on macOS.

No problems with Python 3.7.3 on Debian buster.

**Comment by Mausy5043** [comment] 2020-01-25 16:15
Haven't fully digested it yet, but I feel this may contain a hint of the cause: https://access.redhat.com/articles/2039753

**Comment by brandon-rhodes** [comment] 2020-01-25 16:33
So a missing SSL certificate might be at issue? Interesting. Which raises many of the points brought up here:

https://stackoverflow.com/questions/22027418/openssl-python-requests-error-certificate-verify-failed

@rtphokie — Does the certificate install command fix the situation for you as well? If so then I'll not only add a note to the documentation, but could add a try-except to the Skyfield code so that it prints out a suggestion about running that command if it encounters the error in front of the user!

**Comment by richf27** [comment] 2020-04-20 14:22
Good day. For those of us who are new to python and are experiencing the same SSL issue retrieving this file, what directory should I download this file to? Thanks!

**Comment by brandon-rhodes** [comment] 2020-04-20 16:28
@richf27 Try `load.timescale(builtin=True)`, if you aren't worried about leap-second-level accuracy in the future — would that get your script working again?

Also: you simply download files to the current directly unless you've created a loader that uses some other directly. Where in the docs could I make that clearer so that users know where to put the file? Can you point me at which docs you were following when you ran into the problem? Thanks!

**Comment by brandon-rhodes** [comment] 2020-04-23 17:44
I've just released Skyfield 1.19 which, by moving to the `certifi` set of certificates instead of relying on the operating system's certs found by Python itself, hopefully resolves this issue. I'll close it for now, but please comment further if you still have problems!

**Closed by brandon-rhodes** 2020-04-23 17:44 UTC

**Comment by dearchap** [comment] 2023-11-08 15:24
I still get this error with 1.46. 

```
Traceback (most recent call last):
  File "./main.py", line 10, in <module>
    planets = load('de421.bsp')
  File "/home/deployuser/p3orb/lib/python3.8/site-packages/skyfield/iokit.py", line 193, in __call__
    path = self._assure(url, filename, reload, backup)
  File "/home/deployuser/p3orb/lib/python3.8/site-packages/skyfield/iokit.py", line 214, in _assure
    download(url, path, self.verbose, backup=backup)
  File "/home/deployuser/p3orb/lib/python3.8/site-packages/skyfield/iokit.py", line 525, in download
    raise e2
OSError: cannot download https://ssd.jpl.nasa.gov/ftp/eph/planets/bsp/de421.bsp because <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>
```

**Comment by brandon-rhodes** [comment] 2023-11-13 21:30
@dearchap — Alas, Skyfield isn't directly involved in the SSL computation, so you will need to look up the error message and probably your operating system documentation to learn about why Python on your computer can't make the connection. My advice would be to download the file yourself, so that Skyfield is not involved and you can talk to the Internet directly from your script. I would start by seeing if you can download that URL in your browser, without Python at first being involved.
