### ISSUE TITLE
Unclear behavior and documentation for gmst/gast attributes

### ISSUE THREAD

**Issue by reza-ghazi** [skyfielders/python-skyfield#1025] opened 2024-12-07 20:26 UTC
## Description:
When using a Time object's `gmst` and `gast` attributes, I encountered some difficulties with type handling. The documentation states:

> `gmst`: Greenwich Mean Sidereal Time in hours, in the range 0.0 ≤ gmst < 24.0
> `gast`: Greenwich Apparent Sidereal Time in hours, in the range 0.0 ≤ gast < 24.0

However, these attributes return a `reify` type instead of a float, making direct arithmetic operations impossible. Currently, the workaround is to access the underlying float value using `getattr(time.gmst, '_value')`.

## Suggested improvements:
1. Document the `reify` return type in the API documentation
2. Consider providing a public method to access the numeric value (rather than using the internal `_value` attribute)
3. Or consider having these properties return float values directly since they're documented as numeric hours

**Example of the issue:**
```python
from skyfield.api import load

ts = load.timescale()
t = ts.now()

# The following raises: "Operator '+' not supported for types 'reify' and 'float'"
longitude_hours = 15.0
result = t.gmst + longitude_hours  # TypeError

# Current workaround:
result = getattr(t.gmst, '_value') + longitude_hours  # Works but uses internal attribute
```

**Comment by brandon-rhodes** [comment] 2024-12-07 21:56
Alas, a `TypeError`! We will need to get this fixed for you.

The `@reify` decorator tells Python that when the user asks for `t.gmst`, the function beneath `@reify` should be called instead to get the result. I have added `print(result)` beneath your line `result = t.gmst + longitude_hours` and, on my machine, the script runs without error and prints:

    18.03902196115383

So we have a mystery. Why is a decorator that has been used in the Python community for decades now failing on your machine and Python version? The test I just did was under Python 3.12.1. Could you check which version you are using?

**Comment by reza-ghazi** [comment] 2024-12-09 15:32
I am using Python 3.12.8, which is not the concern.

Let's clarify: I didn't say I got any "TypeError" error. I can also get the result on my machine as you did, but the possible issue (Which is popping up in new linters such as Ruff) is that I can give you a more precise definition or documentation.

You built a class and used it as a decorator, "@reify," which you adapted from the `Pyramid` web Framework. But Python already has the solution. What about `@lru_cache` or the recent one `cache` (Python 3.9+)? They are available with ``` from functools import lru_cache```.

They also have some drawbacks, as the defined class `reify`, but they also have some manageable built-in abilities that make them more reliable.

That is only a suggestion. In my original note, I also suggested some solutions that may be useful.

**Comment by brandon-rhodes** [comment] 2024-12-11 07:02
Oh, good — I'm glad to hear that Python itself is not rejecting your use of `.gmst` and `.gast` as floats! I misunderstood. It sounds like you are using a type checker that is not quite succeeding in figuring out that it should treat `@reify` the same way it treats `@lru_cache` and `@cache`, as wrappers to an underlying value whose type should be used instead. So maybe I could just solve this with an annotation, like those mechanisms probably have.

(Alas, I cannot at this point switch to something like `@cache`, because then the syntax would change to `t.gmst()` with parentheses required, which would break all existing Skyfield programs that use that value.)

Which type checker are you using? I will try installing it, and see if I can get that same error `Operator '+' not supported for types 'reify' and 'float'`.

**Comment by reza-ghazi** [comment] 2024-12-11 19:05
I use Ruff. Which is written in Rust, has a good speed, and is precise. But as you mentioned, they need to adjust their linter. I also have the same issues with some Astropy aspects I didn't have before. For example, it cannot recognize the different units of Astropy and warn me about the missing attributes in "u.deg" or something similar.
However, as we discussed, using the Python built-in libraries is good. I understand it's impossible now, but you can do it soon.

**Comment by reza-ghazi** [comment] 2024-12-11 19:46
**Update:** After investigating, I discovered that the Pylance extension cannot recognize those methods and libraries. Consequently, I uninstalled Pylance, and now Ruff functions effectively without any hassle.

**Comment by brandon-rhodes** [comment] 2024-12-13 23:51
Thank you for tracking down the root cause! I'm glad to hear that Ruff can understand the Python decorator. I am going to close this issue for now, but may re-open it in the future if Skyfield decides to explicitly support Pylance.

**Closed by brandon-rhodes** 2024-12-13 23:51 UTC
